version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "jychp"
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "jychp"
  # Maintain dependencies for golang
  - package-ecosystem: "gomod"
    directory: "/backdoor_src"
    schedule:
      interval: "weekly"
    assignees:
      - "jychp"
